
enum category {
    Travel,
    Mystery,
    Historical_Fiction,
    Sequential_Art,
    Classics,
    Philosophy,
    Romance,
    Womens_Fiction,
    Fiction,
    Childrens,
    Religion,
    Nonfiction,
    Music,
    Default,
    Science_Fiction,
    Sports_and_Games,
    Add_a_comment,
    Fantasy,
    New_Adult,
    Young_Adult,
    Science,
    Poetry,
    Paranormal,
    Art,
    Psychology,
    Autobiography,
    Parenting,
    Adult_Fiction,
    Humor,
    Horror,
    History,
    Food_and_Drink,
    Christian_Fiction,
    Business,
    Biography,
    Thriller,
    Contemporary,
    Spirituality,
    Academic,
    Self_Help,
    Historical,
    Christian,
    Suspense,
    Short_Stories,
    Novels,
    Health,
    Politics,
    Cultural,
    Erotica,
    Crime
}

export interface Book {
    id: Number,
    tilte: string,
    author: string,
    genre: string,
    year: number
}